#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.12
# from Racc grammer file "".
#

require 'racc/parser.rb'

# $Id$
require 'dwek/lexer'
require 'dwek/variable_registry'

module Dwek
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 32)
  attr_reader :mapper_list

  def initialize(verbose = false)
    @verbose = verbose
  end

  def parse(string)
    @variable_registry = VariableRegistry.new
    @mapper_list = MapperList.new

    @lexer = Lexer.new
    @lexer.parse(string)

    do_parse
  end

  def next_token
    @lexer.next_token
  end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    17,     5,     9,     6,    17,    26,    27,    17,    14,    16,
    18,    23,    14,    16,    18,    14,    16,    18,    17,    21,
     5,    17,     6,    19,    25,    10,    14,    16,    18,    14,
    16,    18,    28,     7,    32,    33,    34,    32,    11 ]

racc_action_check = [
    18,     0,     3,     0,    27,    22,    22,     6,    18,    18,
    18,    18,    27,    27,    27,     6,     6,     6,    11,    12,
     2,    34,     2,     7,    21,     4,    11,    11,    11,    34,
    34,    34,    25,     1,    28,    31,    32,    33,     5 ]

racc_action_pointer = [
    -2,    33,    17,     0,    23,    34,     4,    23,   nil,   nil,
   nil,    15,    13,   nil,   nil,   nil,   nil,   nil,    -3,   nil,
   nil,    17,    -9,   nil,   nil,    24,   nil,     1,    24,   nil,
   nil,    26,    32,    27,    18,   nil,   nil ]

racc_action_default = [
   -20,   -20,    -1,   -20,   -20,   -20,   -20,   -20,    -2,    -3,
    -4,   -20,   -20,   -11,   -12,   -13,   -14,   -15,   -20,    37,
    -5,   -20,   -20,   -17,   -18,    -6,   -16,   -20,   -20,   -19,
    -7,    -8,   -20,   -20,   -20,    -9,   -10 ]

racc_goto_table = [
    12,    30,     1,    22,     8,    20,    35,   nil,   nil,   nil,
   nil,   nil,    24,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    29,   nil,   nil,   nil,   nil,   nil,   nil,    36 ]

racc_goto_check = [
     5,     6,     1,    10,     1,     5,     6,   nil,   nil,   nil,
   nil,   nil,     5,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     5,   nil,   nil,   nil,   nil,   nil,   nil,     5 ]

racc_goto_pointer = [
   nil,     2,   nil,   nil,   nil,    -6,   -27,   nil,   nil,   nil,
   -15 ]

racc_goto_default = [
   nil,   nil,     2,     3,     4,   nil,   nil,    31,    13,    15,
   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 17, :_reduce_none,
  2, 17, :_reduce_none,
  2, 18, :_reduce_none,
  2, 18, :_reduce_none,
  3, 19, :_reduce_5,
  4, 20, :_reduce_6,
  6, 20, :_reduce_7,
  1, 22, :_reduce_none,
  3, 22, :_reduce_9,
  3, 23, :_reduce_10,
  1, 21, :_reduce_none,
  1, 21, :_reduce_none,
  1, 21, :_reduce_none,
  1, 21, :_reduce_none,
  1, 24, :_reduce_15,
  3, 25, :_reduce_16,
  2, 25, :_reduce_17,
  1, 26, :_reduce_18,
  3, 26, :_reduce_19 ]

racc_reduce_n = 20

racc_shift_n = 37

racc_token_table = {
  false => 0,
  :error => 1,
  ";" => 2,
  :VARIABLE => 3,
  "=" => 4,
  "MAP" => 5,
  "AS" => 6,
  :MAPPER => 7,
  "WITH" => 8,
  "AND" => 9,
  :OPTION => 10,
  :STRING => 11,
  :NUMBER => 12,
  "[" => 13,
  "]" => 14,
  "," => 15 }

racc_nt_base = 16

racc_use_result_var = false

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\";\"",
  "VARIABLE",
  "\"=\"",
  "\"MAP\"",
  "\"AS\"",
  "MAPPER",
  "\"WITH\"",
  "\"AND\"",
  "OPTION",
  "STRING",
  "NUMBER",
  "\"[\"",
  "\"]\"",
  "\",\"",
  "$start",
  "configuration",
  "expression",
  "assignment",
  "mapping",
  "object",
  "options_list",
  "option",
  "variable",
  "array",
  "array_contents" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

module_eval(<<'.,.,', 'parser.y', 7)
  def _reduce_5(val, _values)
     @variable_registry.set(val[0], val[2]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 9)
  def _reduce_6(val, _values)
     @mapper_list.add_mapper(val[1].to_sym, val[3].to_sym) 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 10)
  def _reduce_7(val, _values)
     @mapper_list.add_mapper(val[1].to_sym, val[3].to_sym, val[5]) 
  end
.,.,

# reduce 8 omitted

module_eval(<<'.,.,', 'parser.y', 13)
  def _reduce_9(val, _values)
     val[2].merge(val[0]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 14)
  def _reduce_10(val, _values)
     { val[0].to_sym => val[2] } 
  end
.,.,

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

module_eval(<<'.,.,', 'parser.y', 17)
  def _reduce_15(val, _values)
     @variable_registry.get(val[0]) 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 19)
  def _reduce_16(val, _values)
     val[1] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 20)
  def _reduce_17(val, _values)
     [] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 21)
  def _reduce_18(val, _values)
     [val[0]] 
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 22)
  def _reduce_19(val, _values)
     val[0] + [val[2]] 
  end
.,.,

def _reduce_none(val, _values)
  val[0]
end

  end   # class Parser
  end   # module Dwek
